### ISSUE TITLE
服务注册中心Eureka模块的配置文件不生效

### ISSUE THREAD

**Issue by pytwj** [wenMN1994/GrainOnlineEducation_Parent#10]
![Uploading image.png…]()

**Comment by pytwj** [comment]
![image](https://user-images.githubusercontent.com/62314967/161388252-39e10c4f-c05c-4190-b63f-790252b660af.png)

**Comment by wenMN1994** [comment]
![image](https://user-images.githubusercontent.com/23701557/162581005-d80d84be-6bec-45cf-8d09-ada7d29ac6d6.png)
配置文件失效的将resources目录标记为Resources Root即可
