### ISSUE TITLE
您好，为何resources文件夹下没有nginx-1.13.8-grain

### ISSUE THREAD

**Issue by wangguangzhong** [wenMN1994/GrainOnlineEducation_Parent#2]
您好，为何resources文件夹下没有nginx-1.13.8-grain

**Comment by wenMN1994** [comment]
之前忘记上传了，还有需要的话你现在可以看一下

**Comment by wangguangzhong** [comment]
那麻烦您上传一下吧，谢谢



---原始邮件---
发件人: "DragonWen"<notifications@github.com&gt;
发送时间: 2020年8月13日(周四) 下午5:38
收件人: "wenMN1994/GrainOnlineEducation_Parent"<GrainOnlineEducation_Parent@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wangguangzhong"<2658675006@qq.com&gt;;
主题: Re: [wenMN1994/GrainOnlineEducation_Parent] 您好，为何resources文件夹下没有nginx-1.13.8-grain (#2)




 
之前忘记上传了，还有需要的话你现在可以看一下
